### PR TITLE
Remove CORS Wildcard

### LINKED ISSUE #477: [Content Bug] Week4 - Step 3:
<https://github.com/bitprj/Intro-To-Serverless/blob/main/.bit/responses/4.3-Week%204%20Step%203.md>

**Identify Steps:**
* Step 3

**Week:**
Week 4

## Describe the Issue

- The section should have a link to a in depth explanation of CORS.
- Wildcard for allowing CORS is usually a no-go with respect to security settings. The host and port used by live server should be entered instead

## Proposed Fix

- Add the link <https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS> to provide more in depth information about CORS
- Do not wildcard the CORS for Azure Functions, but use the host and port used by Live Server (see [settings](https://github.com/ritwickdey/vscode-live-server/blob/master/docs/settings.md))

### PR DESCRIPTION
**Pull request by emsesc**
## Changes made
* Add resource
* Add instructions to use live server port/address

Closes #477

### CODE REVIEW

**Comment by emsesc** [comment]
@lechnerc77 Correct me if I'm wrong, but asking students to just include the live server address in CORS settings will not impact the testing in Cypress, right?

**Comment by lechnerc77** [comment]
@emsesc : Not an expert in that, depends on your cypress setup I would assume. There are some hints in the cypress docu on that (<https://docs.cypress.io/guides/guides/web-security#Limitations>) on how to avoid the pitfalls. A last rescue would be to disable web security for the cypress test (<https://docs.cypress.io/guides/guides/web-security#Disabling-Web-Security>).

Can we try that out before putting it in the documentation?

**Comment by emsesc** [comment]
@lechnerc77 Thanks for the resources and input! I will let you know here once I've tested it out 👍

**Comment by lechnerc77** [comment]
Still WIP

**Pull request closed without merging**
