### PR TITLE
Create setup.sh

### PR DESCRIPTION
**Pull request by dtetreau251**
Here's how students would use the file:
1. Open Terminal: Run sudo chown -R $(whoami) /usr/local/var/homebrew
2. Open Terminal and run the following:
```
bash <(curl -s https://raw.githubusercontent.com/<rest of the file path goes here>)
```
3. When everything completes successfully, close and re-open Terminal. You will see the following insecure directories error message:
```
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? yzsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? y%     ~ $ 
```
Type ‘y’ two times
Run compaudit to see the affected directories
you may then see:
```
There are insecure directories:
/usr/local/share/zsh/site-functions
/usr/local/share/zsh
```
if so:
* run sudo chown -R yourusername /usr/local/share/zsh/site-functions
* run sudo chown -R yourusername /usr/local/share/zsh
4. Run compaudit and you should see the error message(s) cleared

### CODE REVIEW

**Comment by emsesc** [comment]
@dtetreau251 It would be great if you could add these instructions to this [file](https://github.com/bitprj/Intro-To-Serverless/blob/main/GETTING_STARTED.md)!

**Comment by blueboxes** [comment]
I have had an initial read through the script. Looks comprehensive and good to see the difference OS support.

A few thoughts. I think it would be good to include at the start or in the description the tools it will install.

A requirement before this is run is to have a GitHub account setup so worth noting that.

It does not add vscode or azure function tools from my first look so maybe mention these need to be done after.

I will give it a run at some point to test it out.

**Comment by dtetreau251** [comment]
@blueboxes I have proposed some of the changes you recommended in the md file. Thanks!

https://github.com/bitprj/Intro-To-Serverless/pull/319/files

**Comment by blueboxes** [comment]
On a fresh VM I needed to install Git and Curl first but after that, it mostly worked.

I will approve on the fact it may work for some people but think may need work overtime. Maybe we should have a separate script that just checks what's installed and shows a list of ✅ and ❌

Tested

**Review by blueboxes — APPROVED** [review]

**Comment by dtetreau251** [comment]
Thank you!


Sent from Yahoo Mail for iPhone


On Thursday, July 8, 2021, 10:46 AM, John Kilmister ***@***.***> wrote:




On a fresh VM I needed to install Git and Curl first but after that, it mostly worked.

I will approve on the fact it may work for some people but think may need work overtime. Maybe we should have a separate script that just checks what's installed and shows a list of ✅ and ❌

**Comment by dtetreau251** [comment]
The md file mentions installing git along with WSL and a few other things. I'll add apt-get install curl to the md file as one of the pre-requirements for the setup script.

**Pull request merged**
