### PR TITLE
Remove dependency on .bit/.progress

### PR DESCRIPTION
**Pull request by ganning127**
## Changes made
* Added `.bit/progressjs/getProgress.js`, which fetches the current step the user is on using the `hasuraCountQuery` azure function
* Edited the yaml files in the workflows to match

### CODE REVIEW

**Review by emsesc — CHANGES_REQUESTED** [review]
Instead of uploading all the node_modules, you can delete them and instead add this step (be sure to replace with the node modules you used) to every workflow file at the top, preferably after the get count step (this installs node modules on the Github Action)

```yaml
     - name: Install Dependencies
        run: |
          npm install your_module
          npm install your_module
```

**Comment by ganning127** [comment]
After the get count step? Wouldn't the get count step run without mode modules available then?

**Comment by emsesc** [comment]
> After the get count step? Wouldn't the get count step run without mode modules available then?

Oof yeah my bad you're right, you can put it before the get count step

**Review by emsesc — APPROVED** [review]
🧪

**Pull request merged**
