### PR TITLE
rewrote code to find the max value emotion

### LINKED ISSUE #270: Week 2 Step 4 getting max value from JSON object can be simplified
`const main_emotion = Object.keys(emotions).find(key => emotions[key] === Math.max(...objects));` its hard to explain this code to someone who is new to coding / has little experience

### PR DESCRIPTION
**Pull request by ganning127**
Used (in my opinnion) a simplier approach to find the highest value emotion. 

```
function determineDom(emotionJSON) {
    let maxValue = 0;
    let domEmo;

    for (var emo in emotionJSON) {
        if (emotionJSON[emo] > maxValue) {
            maxValue = emotionJSON[emo];
            domEmo = emo;
        }
    }
    return domEmo
}
```

I think this would be easier for beginners to understand, but that might just be me, because it is a little bit more code than the original one line.

Also, we might need to create a video explaining this code if we do use it. It's fine if we don't use this code, i just thought i would rewrite it.

Closes #270

### CODE REVIEW

**Review by emsesc — CHANGES_REQUESTED** [review]
Could you cut down the explanation a little or make it more readable? Currently, it's in a paragraph format that can be hard to digest.

**Comment by blueboxes** [comment]
The other approach to this is to use the JS array.sort then take the top item. That may be even clearer?

**Comment by emsesc** [comment]
> The other approach to this is to use the array.sort then take the top item. That may be even shorter and clearer?

@ganning127 Could you implement this suggestion? This would greatly cut down the code and therefore the explanation as well :)

**Comment by ganning127** [comment]
Great suggestion, I'll break the original line down into smaller chunks & put a little more explanation since it still is pretty concise

**Review by emsesc — APPROVED** [review]
Brilliant explanation 🤯

**Pull request merged**
